name: CI/CD for Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: veli-report
      REGION: europe-west1
      REPOSITORY: crm-realtime
      IMAGE_NAME: static-ip-ingest-service
    steps:
      # ===== Checkout репозитория =====
      - name: Checkout
        uses: actions/checkout@v4

      # ===== Set up Node =====
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      # ===== Install dependencies =====
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      # ===== Run Jest tests =====
      - name: Run Jest tests
        run: yarn test
      
      
      # ===== Set up Docker Buildx =====
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # ===== Авторизация в Google Cloud =====
      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      # ===== Debug info =====
      - name: Debug Info
        run: |
          echo "GitHub SHA: $GITHUB_SHA"
          echo "GCP Project: $GCP_PROJECT"
          echo "Region: $REGION"
          echo "Repository: $REPOSITORY"
          echo "Image: $IMAGE_NAME"
          docker images

      # ===== Build & Push Docker image =====
      - name: Build & Push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --build-arg DATABASE_URL="postgresql://user:pass@localhost:5432/db?schema=public" \
            -t $REGION-docker.pkg.dev/$GCP_PROJECT/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA \
            --push \
            .

      # ===== Verify Docker Push =====
      - name: Verify Docker Push
        run: |
          echo "Docker push completed for $IMAGE_NAME:$GITHUB_SHA"
          docker images | grep $IMAGE_NAME || echo "No local image found"

      # ===== Deploy to Cloud Run =====
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $IMAGE_NAME \
            --image $REGION-docker.pkg.dev/$GCP_PROJECT/$REPOSITORY/$IMAGE_NAME:$GITHUB_SHA \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
